name: Deploy backend on push
on:
  push:
    branches:
      - python-backend_and_DB
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -f Python/Dockerfile -t ${{ secrets.DOCKER_USER }}/mantadive_backend:latest ./Python

      # Step 4: Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/mantadive_backend:latest
